"""initial schema

Revision ID: 0f0b191fb9e8
Revises: 
Create Date: 2026-08-29 10:32:26.320299
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0f0b191fb9e8'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer_inbox',
    sa.Column('consumer_name', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.CHAR(length=26), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('consumer_name', 'event_id', name=op.f('pk_consumer_inbox'))
    )
    op.create_table('idempotency_records',
    sa.Column('actor_id', sa.CHAR(length=26), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.CHAR(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PROCESSING'"), nullable=False),
    sa.Column('resource_id', sa.CHAR(length=26), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status <> 'COMPLETED' OR (http_status IS NOT NULL AND response_body IS NOT NULL)", name=op.f('ck_idempotency_records_completed_has_response')),
    sa.CheckConstraint("status IN ('PROCESSING', 'COMPLETED')", name=op.f('ck_idempotency_records_status_valid')),
    sa.PrimaryKeyConstraint('actor_id', 'endpoint', 'idempotency_key', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('actor_id', 'endpoint', 'idempotency_key', name='natural_key')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.CHAR(length=26), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_outbox_events_attempt_count_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index('ix_outbox_events_unpublished', 'outbox_events', ['next_attempt_at', 'occurred_at'], unique=False, postgresql_where='published_at IS NULL AND dead_lettered_at IS NULL')
    op.create_table('users',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('pin_hash', sa.Text(), nullable=False),
    sa.Column('pin_failed_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pin_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("phone ~ '^01[3-9][0-9]{8}$'", name=op.f('ck_users_phone_format')),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')", name=op.f('ck_users_status_valid')),
    sa.CheckConstraint('pin_failed_attempts >= 0', name=op.f('ck_users_pin_attempts_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('accounts',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('user_id', sa.CHAR(length=26), nullable=True),
    sa.Column('account_type', sa.String(length=30), server_default=sa.text("'USER'"), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'BDT'"), nullable=False),
    sa.Column('balance_minor', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(account_type = 'USER' AND user_id IS NOT NULL) OR (account_type <> 'USER' AND user_id IS NULL)", name=op.f('ck_accounts_ownership_matches_type')),
    sa.CheckConstraint("account_type = 'SYSTEM_ISSUANCE' OR balance_minor >= 0", name=op.f('ck_accounts_user_balance_non_negative')),
    sa.CheckConstraint("account_type IN ('USER', 'SYSTEM_ISSUANCE')", name=op.f('ck_accounts_account_type_valid')),
    sa.CheckConstraint("status IN ('ACTIVE', 'FROZEN', 'CLOSED')", name=op.f('ck_accounts_status_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('account_number', name=op.f('uq_accounts_account_number')),
    sa.UniqueConstraint('user_id', name=op.f('uq_accounts_user_id'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('actor_user_id', sa.CHAR(length=26), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.CHAR(length=26), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('rotated_to_id', sa.CHAR(length=26), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['rotated_to_id'], ['sessions.id'], name=op.f('fk_sessions_rotated_to_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_sessions_refresh_token_hash'))
    )
    op.create_index('ix_sessions_user_id_active', 'sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('sender_account_id', sa.CHAR(length=26), nullable=False),
    sa.Column('receiver_account_id', sa.CHAR(length=26), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('initiated_by_user_id', sa.CHAR(length=26), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('reversal_of_id', sa.CHAR(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('P2P_SEND', 'REQUEST_SETTLEMENT', 'SIGNUP_GRANT', 'REVERSAL')", name=op.f('ck_transfers_kind_valid')),
    sa.CheckConstraint("status IN ('SUCCEEDED', 'FAILED', 'REVERSED')", name=op.f('ck_transfers_status_valid')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_transfers_amount_positive')),
    sa.CheckConstraint('sender_account_id <> receiver_account_id', name=op.f('ck_transfers_sender_differs_from_receiver')),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], name=op.f('fk_transfers_initiated_by_user_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiver_account_id'], ['accounts.id'], name=op.f('fk_transfers_receiver_account_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['transfers.id'], name=op.f('fk_transfers_reversal_of_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sender_account_id'], ['accounts.id'], name=op.f('fk_transfers_sender_account_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfers')),
    sa.UniqueConstraint('reference', name=op.f('uq_transfers_reference'))
    )
    op.create_index('ix_transfers_receiver_created', 'transfers', ['receiver_account_id', 'created_at'], unique=False)
    op.create_index('ix_transfers_sender_created', 'transfers', ['sender_account_id', 'created_at'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('transfer_id', sa.CHAR(length=26), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name=op.f('fk_ledger_transactions_transfer_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_transactions')),
    sa.UniqueConstraint('transfer_id', name=op.f('uq_ledger_transactions_transfer_id'))
    )
    op.create_table('money_requests',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('requester_account_id', sa.CHAR(length=26), nullable=False),
    sa.Column('payer_account_id', sa.CHAR(length=26), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('transfer_id', sa.CHAR(length=26), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'ACCEPTED' AND transfer_id IS NOT NULL) OR (status <> 'ACCEPTED' AND transfer_id IS NULL)", name=op.f('ck_money_requests_transfer_only_when_accepted')),
    sa.CheckConstraint("status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'EXPIRED')", name=op.f('ck_money_requests_status_valid')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_money_requests_amount_positive')),
    sa.CheckConstraint('requester_account_id <> payer_account_id', name=op.f('ck_money_requests_requester_differs_from_payer')),
    sa.ForeignKeyConstraint(['payer_account_id'], ['accounts.id'], name=op.f('fk_money_requests_payer_account_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_account_id'], ['accounts.id'], name=op.f('fk_money_requests_requester_account_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name=op.f('fk_money_requests_transfer_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_money_requests')),
    sa.UniqueConstraint('reference', name=op.f('uq_money_requests_reference')),
    sa.UniqueConstraint('transfer_id', name=op.f('uq_money_requests_transfer_id'))
    )
    op.create_index('ix_money_requests_payer', 'money_requests', ['payer_account_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_money_requests_pending_expiry', 'money_requests', ['expires_at'], unique=False, postgresql_where="status = 'PENDING'")
    op.create_index('ix_money_requests_requester', 'money_requests', ['requester_account_id', 'status', 'created_at'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('ledger_transaction_id', sa.CHAR(length=26), nullable=False),
    sa.Column('account_id', sa.CHAR(length=26), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('balance_after_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor <> 0', name=op.f('ck_ledger_entries_amount_non_zero')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_ledger_entries_account_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ledger_transaction_id'], ['ledger_transactions.id'], name=op.f('fk_ledger_entries_ledger_transaction_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index('ix_ledger_entries_account_id_desc', 'ledger_entries', ['account_id', 'id'], unique=False)
    op.create_index('ix_ledger_entries_txn', 'ledger_entries', ['ledger_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_entries_txn', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_account_id_desc', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_money_requests_requester', table_name='money_requests')
    op.drop_index('ix_money_requests_pending_expiry', table_name='money_requests', postgresql_where="status = 'PENDING'")
    op.drop_index('ix_money_requests_payer', table_name='money_requests')
    op.drop_table('money_requests')
    op.drop_table('ledger_transactions')
    op.drop_index('ix_transfers_sender_created', table_name='transfers')
    op.drop_index('ix_transfers_receiver_created', table_name='transfers')
    op.drop_table('transfers')
    op.drop_index('ix_sessions_user_id_active', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_index('ix_outbox_events_unpublished', table_name='outbox_events', postgresql_where='published_at IS NULL AND dead_lettered_at IS NULL')
    op.drop_table('outbox_events')
    op.drop_table('idempotency_records')
    op.drop_table('consumer_inbox')
    # ### end Alembic commands ###
