"""advanced features: subaccounts, scheduler, escrow, groups, links, overdraft

Revision ID: 62e621b0ed86
Revises: 0f0b191fb9e9
Create Date: 2026-08-29 12:10:55.028313
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '62e621b0ed86'
down_revision: str | None = '0f0b191fb9e9'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('resource_id', sa.CHAR(length=26), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'DONE', 'CANCELLED', 'FAILED')", name=op.f('ck_scheduled_tasks_status_valid')),
    sa.CheckConstraint("task_type IN ('UNDO_SETTLE', 'ESCROW_AUTO_RELEASE', 'LINK_EXPIRY', 'MONEY_REQUEST_EXPIRY')", name=op.f('ck_scheduled_tasks_task_type_valid')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_scheduled_tasks_attempt_count_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_tasks')),
    sa.UniqueConstraint('task_type', 'resource_id', name='one_task_per_resource')
    )
    op.create_index('ix_scheduled_tasks_due', 'scheduled_tasks', ['due_at'], unique=False, postgresql_where="status = 'PENDING'")
    op.create_table('group_wallets',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_by_user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('quorum_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'CLOSED')", name=op.f('ck_group_wallets_status_valid')),
    sa.CheckConstraint('quorum_size >= 1', name=op.f('ck_group_wallets_quorum_at_least_one')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_group_wallets_account_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_group_wallets_created_by_user_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_wallets')),
    sa.UniqueConstraint('account_id', name=op.f('uq_group_wallets_account_id'))
    )
    op.create_table('overdraft_pools',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('sponsor_user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('pool_account_id', sa.CHAR(length=26), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')", name=op.f('ck_overdraft_pools_status_valid')),
    sa.ForeignKeyConstraint(['pool_account_id'], ['accounts.id'], name=op.f('fk_overdraft_pools_pool_account_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sponsor_user_id'], ['users.id'], name=op.f('fk_overdraft_pools_sponsor_user_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_overdraft_pools')),
    sa.UniqueConstraint('pool_account_id', name=op.f('uq_overdraft_pools_pool_account_id')),
    sa.UniqueConstraint('sponsor_user_id', name='one_pool_per_sponsor')
    )
    op.create_table('payment_links',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('payee_account_id', sa.CHAR(length=26), nullable=False),
    sa.Column('payee_user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('fixed_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('max_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('max_uses', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('uses_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('single_use', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'CONSUMED', 'EXPIRED', 'REVOKED')", name=op.f('ck_payment_links_status_valid')),
    sa.CheckConstraint('fixed_amount_minor IS NULL OR (fixed_amount_minor > 0 AND fixed_amount_minor <= max_amount_minor)', name=op.f('ck_payment_links_fixed_amount_within_cap')),
    sa.CheckConstraint('max_amount_minor > 0', name=op.f('ck_payment_links_max_amount_positive')),
    sa.CheckConstraint('max_uses >= 1', name=op.f('ck_payment_links_max_uses_at_least_one')),
    sa.CheckConstraint('uses_count >= 0 AND uses_count <= max_uses', name=op.f('ck_payment_links_uses_within_cap')),
    sa.ForeignKeyConstraint(['payee_account_id'], ['accounts.id'], name=op.f('fk_payment_links_payee_account_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payee_user_id'], ['users.id'], name=op.f('fk_payment_links_payee_user_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_links')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_payment_links_token_hash'))
    )
    op.create_index('ix_payment_links_active_expiry', 'payment_links', ['expires_at'], unique=False, postgresql_where="status = 'ACTIVE'")
    op.create_index('ix_payment_links_payee', 'payment_links', ['payee_user_id', 'status', 'created_at'], unique=False)
    op.create_table('group_members',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('group_id', sa.CHAR(length=26), nullable=False),
    sa.Column('user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('role', sa.String(length=30), server_default=sa.text("'MEMBER'"), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('ADMIN', 'MEMBER')", name=op.f('ck_group_members_role_valid')),
    sa.ForeignKeyConstraint(['group_id'], ['group_wallets.id'], name=op.f('fk_group_members_group_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_members_user_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_members')),
    sa.UniqueConstraint('group_id', 'user_id', name='one_membership_per_user')
    )
    op.create_index('ix_group_members_user', 'group_members', ['user_id', 'left_at'], unique=False)
    op.create_table('group_withdrawal_requests',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('group_id', sa.CHAR(length=26), nullable=False),
    sa.Column('requested_by_user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('to_account_id', sa.CHAR(length=26), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('transfer_id', sa.CHAR(length=26), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'EXECUTED' AND transfer_id IS NOT NULL) OR (status <> 'EXECUTED' AND transfer_id IS NULL)", name=op.f('ck_group_withdrawal_requests_executed_has_transfer')),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'EXECUTED', 'REJECTED', 'CANCELLED', 'EXPIRED')", name=op.f('ck_group_withdrawal_requests_status_valid')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_group_withdrawal_requests_amount_positive')),
    sa.ForeignKeyConstraint(['group_id'], ['group_wallets.id'], name=op.f('fk_group_withdrawal_requests_group_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_group_withdrawal_requests_requested_by_user_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], name=op.f('fk_group_withdrawal_requests_to_account_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name=op.f('fk_group_withdrawal_requests_transfer_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_withdrawal_requests')),
    sa.UniqueConstraint('reference', name=op.f('uq_group_withdrawal_requests_reference')),
    sa.UniqueConstraint('transfer_id', name=op.f('uq_group_withdrawal_requests_transfer_id'))
    )
    op.create_index('ix_group_withdrawals_group', 'group_withdrawal_requests', ['group_id', 'status', 'created_at'], unique=False)
    op.create_table('overdraft_grants',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('pool_id', sa.CHAR(length=26), nullable=False),
    sa.Column('beneficiary_user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('max_draw_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'REVOKED')", name=op.f('ck_overdraft_grants_status_valid')),
    sa.CheckConstraint('max_draw_minor > 0', name=op.f('ck_overdraft_grants_max_draw_positive')),
    sa.ForeignKeyConstraint(['beneficiary_user_id'], ['users.id'], name=op.f('fk_overdraft_grants_beneficiary_user_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pool_id'], ['overdraft_pools.id'], name=op.f('fk_overdraft_grants_pool_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_overdraft_grants')),
    sa.UniqueConstraint('pool_id', 'beneficiary_user_id', name='one_grant_per_beneficiary')
    )
    op.create_index('ix_overdraft_grants_beneficiary', 'overdraft_grants', ['beneficiary_user_id', 'status'], unique=False)
    op.create_table('overdraft_loans',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('pool_id', sa.CHAR(length=26), nullable=False),
    sa.Column('borrower_user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('draw_transfer_id', sa.CHAR(length=26), nullable=False),
    sa.Column('principal_minor', sa.BigInteger(), nullable=False),
    sa.Column('outstanding_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'OUTSTANDING'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('repaid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'REPAID' AND outstanding_minor = 0) OR status <> 'REPAID'", name=op.f('ck_overdraft_loans_repaid_means_zero')),
    sa.CheckConstraint("status IN ('OUTSTANDING', 'REPAID', 'WRITTEN_OFF')", name=op.f('ck_overdraft_loans_status_valid')),
    sa.CheckConstraint('outstanding_minor >= 0 AND outstanding_minor <= principal_minor', name=op.f('ck_overdraft_loans_outstanding_within_principal')),
    sa.CheckConstraint('principal_minor > 0', name=op.f('ck_overdraft_loans_principal_positive')),
    sa.ForeignKeyConstraint(['borrower_user_id'], ['users.id'], name=op.f('fk_overdraft_loans_borrower_user_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['draw_transfer_id'], ['transfers.id'], name=op.f('fk_overdraft_loans_draw_transfer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pool_id'], ['overdraft_pools.id'], name=op.f('fk_overdraft_loans_pool_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_overdraft_loans')),
    sa.UniqueConstraint('draw_transfer_id', name=op.f('uq_overdraft_loans_draw_transfer_id'))
    )
    op.create_index('ix_overdraft_loans_borrower_outstanding', 'overdraft_loans', ['borrower_user_id'], unique=False, postgresql_where="status = 'OUTSTANDING'")
    op.create_table('payment_link_payments',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('link_id', sa.CHAR(length=26), nullable=False),
    sa.Column('transfer_id', sa.CHAR(length=26), nullable=False),
    sa.Column('payer_user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_payment_link_payments_amount_positive')),
    sa.ForeignKeyConstraint(['link_id'], ['payment_links.id'], name=op.f('fk_payment_link_payments_link_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payer_user_id'], ['users.id'], name=op.f('fk_payment_link_payments_payer_user_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name=op.f('fk_payment_link_payments_transfer_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_link_payments')),
    sa.UniqueConstraint('transfer_id', name=op.f('uq_payment_link_payments_transfer_id'))
    )
    op.create_index('ix_link_payments_link', 'payment_link_payments', ['link_id', 'created_at'], unique=False)
    op.create_table('safepay_escrows',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('hold_transfer_id', sa.CHAR(length=26), nullable=False),
    sa.Column('settlement_transfer_id', sa.CHAR(length=26), nullable=True),
    sa.Column('buyer_user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('seller_user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'AWAITING_SHIPMENT'"), nullable=False),
    sa.Column('delivery_code_hash', sa.Text(), nullable=False),
    sa.Column('delivery_code_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('delivery_code_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_number', sa.String(length=64), nullable=True),
    sa.Column('courier_slug', sa.String(length=32), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_release_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_reason', sa.String(length=500), nullable=True),
    sa.Column('disputed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.CHAR(length=26), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status IN ('RELEASED', 'REFUNDED') AND settlement_transfer_id IS NOT NULL) OR (status NOT IN ('RELEASED', 'REFUNDED') AND settlement_transfer_id IS NULL)", name=op.f('ck_safepay_escrows_settled_has_settlement_leg')),
    sa.CheckConstraint("status IN ('AWAITING_SHIPMENT', 'SHIPPED', 'DELIVERED', 'RELEASED', 'REFUNDED', 'DISPUTED', 'CANCELLED')", name=op.f('ck_safepay_escrows_status_valid')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_safepay_escrows_amount_positive')),
    sa.CheckConstraint('buyer_user_id <> seller_user_id', name=op.f('ck_safepay_escrows_buyer_differs_from_seller')),
    sa.CheckConstraint('delivery_code_attempts >= 0', name=op.f('ck_safepay_escrows_attempts_non_negative')),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], name=op.f('fk_safepay_escrows_buyer_user_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hold_transfer_id'], ['transfers.id'], name=op.f('fk_safepay_escrows_hold_transfer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('fk_safepay_escrows_resolved_by_user_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], name=op.f('fk_safepay_escrows_seller_user_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_transfer_id'], ['transfers.id'], name=op.f('fk_safepay_escrows_settlement_transfer_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safepay_escrows')),
    sa.UniqueConstraint('hold_transfer_id', name=op.f('uq_safepay_escrows_hold_transfer_id')),
    sa.UniqueConstraint('reference', name=op.f('uq_safepay_escrows_reference')),
    sa.UniqueConstraint('settlement_transfer_id', name=op.f('uq_safepay_escrows_settlement_transfer_id'))
    )
    op.create_index('ix_safepay_buyer', 'safepay_escrows', ['buyer_user_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_safepay_seller', 'safepay_escrows', ['seller_user_id', 'status', 'created_at'], unique=False)
    op.create_table('group_withdrawal_approvals',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('request_id', sa.CHAR(length=26), nullable=False),
    sa.Column('approver_user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVE', 'REJECT')", name=op.f('ck_group_withdrawal_approvals_decision_valid')),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], name=op.f('fk_group_withdrawal_approvals_approver_user_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['group_withdrawal_requests.id'], name=op.f('fk_group_withdrawal_approvals_request_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_withdrawal_approvals')),
    sa.UniqueConstraint('request_id', 'approver_user_id', name='one_vote_per_member')
    )
    op.create_table('overdraft_repayments',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('loan_id', sa.CHAR(length=26), nullable=False),
    sa.Column('transfer_id', sa.CHAR(length=26), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('triggered_by_transfer_id', sa.CHAR(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_overdraft_repayments_amount_positive')),
    sa.ForeignKeyConstraint(['loan_id'], ['overdraft_loans.id'], name=op.f('fk_overdraft_repayments_loan_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name=op.f('fk_overdraft_repayments_transfer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['triggered_by_transfer_id'], ['transfers.id'], name=op.f('fk_overdraft_repayments_triggered_by_transfer_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_overdraft_repayments')),
    sa.UniqueConstraint('transfer_id', name=op.f('uq_overdraft_repayments_transfer_id'))
    )
    op.create_index('ix_overdraft_repayments_loan', 'overdraft_repayments', ['loan_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('uq_accounts_user_id'), 'accounts', type_='unique')
    op.create_unique_constraint('one_account_per_user_per_type', 'accounts', ['user_id', 'account_type'])
    op.add_column('transfers', sa.Column('parent_transfer_id', sa.CHAR(length=26), nullable=True))
    op.create_foreign_key(op.f('fk_transfers_parent_transfer_id'), 'transfers', 'transfers', ['parent_transfer_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint(op.f('ck_transfers_settlement_leg_has_parent'), 'transfers', "(kind IN ('UNDO_SETTLE', 'UNDO_REFUND', 'ESCROW_RELEASE', 'ESCROW_REFUND') AND parent_transfer_id IS NOT NULL) OR (kind NOT IN ('UNDO_SETTLE', 'UNDO_REFUND', 'ESCROW_RELEASE', 'ESCROW_REFUND') AND parent_transfer_id IS NULL)")
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Modified CHECK constraints.
    #
    # Alembic autogenerate diffs tables, columns and indexes, but it cannot
    # diff a CHANGED check constraint - it sees the name on both sides and
    # reports no difference. Every constraint below is therefore dropped and
    # recreated explicitly. Missing this would leave the database still
    # rejecting the very account types and transfer kinds this migration
    # exists to allow, and the failure would only surface at runtime.
    # ------------------------------------------------------------------
    op.drop_constraint(op.f("ck_accounts_account_type_valid"), "accounts", type_="check")
    op.create_check_constraint(
        "account_type_valid",
        "accounts",
        "account_type IN ('USER', 'SYSTEM_ISSUANCE', 'PENDING_SETTLEMENT', "
        "'ESCROW', 'GROUP', 'OVERDRAFT_POOL')",
    )

    # Relaxed so an account can be owned by a user (main, overdraft pool) or by
    # nobody (system holding accounts, group wallets), but never mismatched.
    op.drop_constraint(op.f("ck_accounts_ownership_matches_type"), "accounts", type_="check")
    op.create_check_constraint(
        "ownership_matches_type",
        "accounts",
        "(account_type IN ('USER', 'OVERDRAFT_POOL') AND user_id IS NOT NULL) OR "
        "(account_type IN ('SYSTEM_ISSUANCE', 'ESCROW', 'PENDING_SETTLEMENT', "
        "'GROUP') AND user_id IS NULL)",
    )

    op.drop_constraint(op.f("ck_transfers_kind_valid"), "transfers", type_="check")
    op.create_check_constraint(
        "kind_valid",
        "transfers",
        "kind IN ('P2P_SEND', 'REQUEST_SETTLEMENT', 'SIGNUP_GRANT', 'REVERSAL',"
        " 'UNDO_HOLD', 'UNDO_SETTLE', 'UNDO_REFUND',"
        " 'ESCROW_HOLD', 'ESCROW_RELEASE', 'ESCROW_REFUND',"
        " 'GROUP_DEPOSIT', 'GROUP_WITHDRAWAL', 'LINK_PAYMENT',"
        " 'OVERDRAFT_DRAW', 'OVERDRAFT_REPAY', 'OVERDRAFT_FUND')",
    )

    op.drop_constraint(op.f("ck_transfers_status_valid"), "transfers", type_="check")
    op.create_check_constraint(
        "status_valid",
        "transfers",
        "status IN ('SUCCEEDED', 'FAILED', 'REVERSED', 'PENDING_UNDO', "
        "'HELD', 'DISPUTED', 'REFUNDED')",
    )

    # ------------------------------------------------------------------
    # System holding accounts.
    #
    # Money mid-flight is parked in a real account, never left in the payer's
    # balance behind a status flag. A flag does not stop a concurrent transfer
    # from spending the same taka; moving it does, because the ordinary
    # balance check then does the work.
    # ------------------------------------------------------------------
    for account_id, account_type, number in (
        ("00000000000000000000000001", "ESCROW", "SYS-ESCROW-001"),
        ("00000000000000000000000002", "PENDING_SETTLEMENT", "SYS-PENDING-001"),
    ):
        op.execute(
            sa.text(
                """
                INSERT INTO accounts (
                    id, user_id, account_type, account_number, currency,
                    balance_minor, status, version, created_at, updated_at
                ) VALUES (
                    :id, NULL, :atype, :num, 'BDT', 0, 'ACTIVE', 0, now(), now()
                )
                ON CONFLICT (id) DO NOTHING
                """
            ).bindparams(id=account_id, atype=account_type, num=number)
        )

    # The runtime role must be able to use the new tables.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO mm_app")
    op.execute("GRANT SELECT ON ALL TABLES IN SCHEMA public TO mm_readonly")
    # The blanket grant above includes pre-existing tables. Reassert the two
    # append-only boundaries so this migration cannot silently weaken them.
    op.execute("REVOKE UPDATE, DELETE ON ledger_entries FROM mm_app")
    op.execute("REVOKE UPDATE, DELETE ON ledger_transactions FROM mm_app")
    op.execute("REVOKE UPDATE, DELETE ON audit_logs FROM mm_app")



def downgrade() -> None:

    op.execute(
        "DELETE FROM accounts WHERE account_type IN ('ESCROW', 'PENDING_SETTLEMENT')"
    )
    op.drop_constraint(op.f("ck_transfers_status_valid"), "transfers", type_="check")
    op.create_check_constraint(
        "status_valid", "transfers",
        "status IN ('SUCCEEDED', 'FAILED', 'REVERSED')",
    )
    op.drop_constraint(op.f("ck_transfers_kind_valid"), "transfers", type_="check")
    op.create_check_constraint(
        "kind_valid", "transfers",
        "kind IN ('P2P_SEND', 'REQUEST_SETTLEMENT', 'SIGNUP_GRANT', 'REVERSAL')",
    )
    op.drop_constraint(op.f("ck_accounts_ownership_matches_type"), "accounts", type_="check")
    op.create_check_constraint(
        "ownership_matches_type", "accounts",
        "(account_type = 'USER' AND user_id IS NOT NULL) OR "
        "(account_type <> 'USER' AND user_id IS NULL)",
    )
    op.drop_constraint(op.f("ck_accounts_account_type_valid"), "accounts", type_="check")
    op.create_check_constraint(
        "account_type_valid", "accounts",
        "account_type IN ('USER', 'SYSTEM_ISSUANCE')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_transfers_settlement_leg_has_parent'), 'transfers', type_='check')
    op.drop_constraint(op.f('fk_transfers_parent_transfer_id'), 'transfers', type_='foreignkey')
    op.drop_column('transfers', 'parent_transfer_id')
    op.drop_constraint('one_account_per_user_per_type', 'accounts', type_='unique')
    op.create_unique_constraint(op.f('uq_accounts_user_id'), 'accounts', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_overdraft_repayments_loan', table_name='overdraft_repayments')
    op.drop_table('overdraft_repayments')
    op.drop_table('group_withdrawal_approvals')
    op.drop_index('ix_safepay_seller', table_name='safepay_escrows')
    op.drop_index('ix_safepay_buyer', table_name='safepay_escrows')
    op.drop_table('safepay_escrows')
    op.drop_index('ix_link_payments_link', table_name='payment_link_payments')
    op.drop_table('payment_link_payments')
    op.drop_index('ix_overdraft_loans_borrower_outstanding', table_name='overdraft_loans', postgresql_where="status = 'OUTSTANDING'")
    op.drop_table('overdraft_loans')
    op.drop_index('ix_overdraft_grants_beneficiary', table_name='overdraft_grants')
    op.drop_table('overdraft_grants')
    op.drop_index('ix_group_withdrawals_group', table_name='group_withdrawal_requests')
    op.drop_table('group_withdrawal_requests')
    op.drop_index('ix_group_members_user', table_name='group_members')
    op.drop_table('group_members')
    op.drop_index('ix_payment_links_payee', table_name='payment_links')
    op.drop_index('ix_payment_links_active_expiry', table_name='payment_links', postgresql_where="status = 'ACTIVE'")
    op.drop_table('payment_links')
    op.drop_table('overdraft_pools')
    op.drop_table('group_wallets')
    op.drop_index('ix_scheduled_tasks_due', table_name='scheduled_tasks', postgresql_where="status = 'PENDING'")
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
