"""hold intended receiver

Revision ID: 8ddea5c31c8a
Revises: 62e621b0ed86
Create Date: 2026-08-29 12:16:56.261328
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '8ddea5c31c8a'
down_revision: str | None = '62e621b0ed86'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('intended_receiver_account_id', sa.CHAR(length=26), nullable=True))
    op.create_foreign_key(op.f('fk_transfers_intended_receiver_account_id'), 'transfers', 'accounts', ['intended_receiver_account_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transfers_intended_receiver_account_id'), 'transfers', type_='foreignkey')
    op.drop_column('transfers', 'intended_receiver_account_id')
    # ### end Alembic commands ###
